config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  get 'about' => 'about#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers

  root 'books#index'
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books

  validates :first_name, presence: true,
                         length: { minimum: 3 }
  validates :last_name, presence: true,
                         length: { minimum: 3 }
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  belongs_to :author
  belongs_to :publisher

  validates :title, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books

  validates :name, presence: true, length: { minimum: 3 }
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
  validates :name, presence: true, length: { minimum: 3 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = "About us"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :find_id, only: [:edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def new
    @page_title = 'Add New Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      flash[:success] = @author.first_name + ' ' + @author.last_name + ' created.'
      redirect_to authors_path
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @author.update(author_params)
      flash[:success] = @author.first_name + ' ' + @author.last_name + ' updated.'
      redirect_to authors_path
    else
      render :new
    end
  end

  def destroy
    if @author.destroy
      flash[:success] = @author.first_name + ' ' + @author.last_name + ' was deleted.'
      redirect_to authors_path
    end
  end

  private

  def find_id
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_id, only: [:edit, :show, :update, :destroy]

  def index
    @books = Book.all
    @categories = Category.all
  end

  def new
    @page_title = 'Add Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:success] = @book.title + ' created.'
      redirect_to books_path
    else
      render :new
    end
  end

  def show
    @categories = Category.all
  end

  def edit
    render :new
  end

  def update
    if @book.update(book_params)
      flash[:success] = @book.title + ' updated.'
      redirect_to books_path
    else
      render :new
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = @book.title + ' was deleted.'
      redirect_to books_path
    end
  end

  private

  def find_id
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :price, :buy, :format, :excerpt, :pages, :year, :coverpath)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_id, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @page_title = 'Add New Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = @category.title + ' created.'
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def show
    @category = Category.find(params[:id])
    @books = @category.books
    @categories = Category.all
  end

  def update
    if @category.update(category_params)
      flash[:success] = @category.title + ' updated.'
      redirect_to categories_path
    else
      render :new
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = @category.name + ' was deleted.'
      redirect_to categories_path
    end
  end

  private

  def find_id
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :find_id, only: [:edit, :update, :destroy]

  def index
    @publishers = Publisher.all
  end

  def new
    @page_title = 'Add New Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)

    if @publisher.save
      redirect_to publishers_path
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @publisher.update(publisher_params)
      redirect_to publishers_path
    else
      render :new
    end
  end

  def destroy
    if @publisher.destroy
      flash[:success] = @publisher.name + ' was deleted.'
      redirect_to publishers_path
    end
  end

  private

  def find_id
    @publisher = Publisher.find(params[:id])
  end

  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def render_flash
    render 'application/flash' if can_flash?
  end

  def can_flash?
    flash.keys.sort == ['from', 'full_messages', 'object_id', 'object_type', 'type']
  end

  def flash_object
    flash[:object_type].classify.constantize.where(id: flash[:object_id]).first
  end

  def flash_path
    [controller_name, 'flash'].join('/')
  end

  # def render_flash_file
  #   begin
  #     render flash_path, object: flash_object
  #   rescue Exception => e
  #     if e.class.name == 'ActionView::MissingTemplate'
  #       render html: '<h4>Errors</h4>'.html_safe
  #     else
  #       raise e
  #     end
  #   end
  # end

  def flash_messages
    flash[:full_messages]
  end
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/application/_destroy.html.erb
<div class="alert alert-<%= flash[:type] == 'success' ? 'info' : 'danger' %>">
  <div class="container">
    <%= render flash_path, object: flash_object %>

    <% if flash_messages %>

      <ul>
        <% flash_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    <% end %>

  </div>
</div>

app/views/application/_flash.html.erb
<div class="alert alert-<%= flash[:type] == 'success' ? 'info' : 'danger' %>">
  <div class="container">
    <%= render flash_path, object: flash_object %>

    <% if flash_messages %>

      <ul>
        <% flash_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    <% end %>

  </div>
</div>

app/views/authors/_flash.html.erb
<% if flash[:type] == 'success' %>

  <h4>Congratulations</h4>
  Your author has been successfully <%= flash[:from] %>d! <%= link_to "edit: #{object.first_name} #{object.last_name}", edit_author_path(object) %>

<% else %>

  <h4>Check your entries</h4>

<% end %>

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, class:'form-control' %><br />
  </div>

  <%=link_to "Cancel", authors_path, class:'btn btn-default' %>

  <% if @author[:id] %>
    <%= link_to "Delete", author_path(@author), method: :delete, data: { confirm: "Are you sure?" }, class:'btn btn-danger' %>
  <% end %>

  <%= f.submit "Submit", class:'btn btn-primary' %>

<% end %>

app/views/authors/index.html.erb
<div>
  <h2 class="pull-left">Book Authors</h2>
  <%= link_to 'Add new', new_author_path, class: 'btn btn-default pull-right' %>
</div>

<table class="table table-striped">
  <tr>
   <th>Author Name</th>
   <th>Actions</th>
  </tr>
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.first_name + ' ' + author.last_name %></td>
      <td><%= link_to 'Edit', edit_author_path(author) %> | <%= link_to 'Delete', author_path(author), method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/authors/new.html.erb
<h2><%= params[:action] == 'update' ? 'Edit' : 'Add New' %> Author</h2>
<%= render partial: 'form' %>

app/views/books/index.html.erb
<div id="books-index">

  <% @books.each_slice(4) do |book_grp| %>
    <div class="row">
      <% book_grp.each do |book| %>
      <div class="col-md-3 col-sm-3">
        <h3>
          <%= book.title %>
        </h3>
        <%= image_tag(book.coverpath) %>
        <%= link_to 'Read More', book_path(book), class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  <% end %>

</div>

app/views/books/new.html.erb
<h2>Add New Book</h2>

<%= form_for @book do |f| %>

  <% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn ,class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :category %><br />
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br /><br />
  </div>

  <div class="form-group">
    <%= f.label :author %><br />
    <%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br /><br />
  </div>

  <div class="form-group">
    <%= f.label :publisher %><br />
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br /><br />
  </div>

  <div class="form-group">
    <%= f.label :format %><br />
    <%= f.text_field :format ,class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :excerpt %><br />
    <%= f.text_area :excerpt ,class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :pages %><br />
    <%= f.number_field :pages ,class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :price %><br />
    <%= f.text_field :price ,class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :buy %><br />
    <%= f.text_field :buy ,class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :year %><br />
    <%= f.text_field :year ,class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :coverpath %><br />
    <%= f.text_field :coverpath ,class:'form-control' %><br />
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%=link_to "Cancel", books_path, class:'btn btn-default' %>

<% end %>

app/views/books/show.html.erb
<div id="books-show">
  <h2><% @book.title %></h2>
  <div class="books-show-left">
    <%= image_tag(@book.coverpath) %>
  </div>
  <div class="books-show-right">
    <h3>Book info:</h3>
    <ul>
      <li><strong>Category: </strong><%= @book.category.name %></li>
      <li><strong>Author: </strong><%= "#{@book.author.first_name} #{@book.author.last_name}" %></li>
      <li><strong>Publisher: </strong><%= @book.publisher.name %></li>
      <li><strong>Year: </strong><%= @book.year %></li>
      <li><strong>ISBN: </strong><%= @book.isbn %></li>
      <li><strong>Format: </strong><%= @book.format %></li>
      <li><strong>Pages: </strong><%= @book.pages %></li>
    </ul>
  </div>
  <%= link_to "Buy for #{@book.price}", @book.buy, class: 'btn btn-success', target: '_blank' %>
  <div class="clearfix"></div>
  <h4>Excerpt:</h4>
  <p><%= @book.excerpt %></p>
  <hr>

  <div class="container">
    <h4>Admin Functions</h4>
    <%= link_to 'Delete', book_path(@book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-info' %>
  </div>
</div>

app/views/categories/_flash.html.erb
<% if flash[:type] == 'success' %>

  <h4>Congratulations</h4>
  Your category has been successfully <%= flash[:from] %>d! <%= link_to "edit: #{object.name}", edit_category_path(object) %>

<% else %>

  <h4>Check your entries</h4>

<% end %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:'form-control' %><br />
  </div>

  <%= link_to "Cancel", categories_path, class:'btn btn-default' %>

  <% if @category[:id] %>
    <%= link_to "Delete", category_path(@category), method: :delete, data: { confirm: "Are you sure?" }, class:'btn btn-danger' %>
  <% end %>

  <%= f.submit "Submit", class:'btn btn-primary' %>

<% end %>

app/views/categories/index.html.erb
<div>
  <h2 class="pull-left">Book Categories</h2>
  <%= link_to 'Add new', new_category_path, class: 'btn btn-default pull-right' %>
</div>

<table class="table table-striped">
  <tr>
   <th>Category Name</th>
   <th>Actions</th>
  </tr>
  <% @categories.each do |cat| %>
    <tr>
      <td><%= cat.name %></td>
      <td><%= link_to 'Edit', edit_category_path(cat) %> | <%= link_to 'Delete', category_path(cat), method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h2><%= params[:action] == 'update' ? 'Edit' : 'Add New' %> Category</h2>
<%= render partial: 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<div id="books-index">

  <% @books.each_slice(4) do |book_grp| %>
    <div class="row">
      <% book_grp.each do |book| %>
      <div class="col-md-3 col-sm-3">
        <h3><%= book.title %> <%= link_to 'del', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></h3>
        <%= image_tag(book.coverpath) %>
        <%= link_to 'Read More', book_path(book), class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bookstore <%= @page_title ? @page_title : 'Welcome' %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
          <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add new <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Book', new_book_path %></li>
              <li><%= link_to 'Category', new_category_path %></li>
              <li><%= link_to 'Author', new_author_path %></li>
              <li><%= link_to 'Publisher', new_publisher_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Categories', categories_path %></li>
              <li><%= link_to 'Authors', authors_path %></li>
              <li><%= link_to 'Publishers', publishers_path %></li>
            </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <header>
    <div class="container">
      <h1>The BookStore <small><%= @page_title ? @page_title : 'Welcome' %></small></h1>
    </div>
  </header>

  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-8">

          <% if flash[:success] %>
            <div class="alert alert-success">
              <div class="container">
                <%= flash[:success] %>
              </div>
            </div>
          <% end %>

          <%= yield %>
        </div>
        <div class="col-md-4">
          <%= render 'partials/sidebar' %>
        </div>
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <p>Copyright 2016 All rights reserved</p>
    </div>
  </footer>

</body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>

  <div class="well">
    <h3>Location Info</h3>
    <ul>
      <li>The Bookstore</li>
      <li>242 Ipil corner Epifanio Sts.</li>
      <li>Santolan, Palayan City</li>
      <li>Phone: 0935.535.6014</li>
      <li>Email: support@thebookstore.com</li>
    </ul>
  </div>
<% end %>

<% if (params[:controller] == 'books' && ['index', 'show'].include?(params[:action])) || (params[:controller] == 'categories' && params[:action] == 'show') %>
  <div class="list-group">
    <%= link_to 'All Books', books_path, class: 'list-group-item' %>
    <% @categories.each do |cat| %>
      <%= link_to cat.name, category_path(cat), class: 'list-group-item' %>
    <% end %>
  </div>
<% end %>

app/views/publishers/_flash.html.erb
<% if flash[:type] == 'success' %>

  <h4>Congratulations</h4>
  Your publisher has been successfully <%= flash[:from] %>d! <%= link_to "edit: #{object.name}", edit_publisher_path(object) %>

<% else %>

  <h4>Check your entries</h4>

<% end %>

app/views/publishers/_form.html.erb
<%= form_for @publisher do |f| %>

  <% if @publisher.errors.any? %>
    <% @publisher.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:'form-control' %><br />
  </div>

  <%=link_to "Cancel", publishers_path, class:'btn btn-default' %>

  <% if @publisher[:id] %>
    <%= link_to "Delete", publisher_path(@publisher), method: :delete, data: { confirm: "Are you sure?" }, class:'btn btn-danger' %>
  <% end %>

  <%= f.submit "Submit", class:'btn btn-primary' %>

<% end %>

app/views/publishers/index.html.erb
<div>
  <h2 class="pull-left">Book Publishers</h2>
  <%= link_to 'Add new', new_publisher_path, class: 'btn btn-default pull-right' %>
</div>

<table class="table table-striped">
  <tr>
   <th>Publisher Name</th>
   <th>Actions</th>
  </tr>
  <% @publishers.each do |pub| %>
    <tr>
      <td><%= pub.name %></td>
      <td><%= link_to 'Edit', edit_publisher_path(pub) %> | <%= link_to 'Delete', publisher_path(pub), method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/publishers/new.html.erb
<h2><%= params[:action] == 'update' ? 'Edit' : 'Add New' %> Publisher</h2>
<%= render 'form' %>